jcapote_to_do_homepage:
    path:     /
    defaults: { _controller: JcapoteToDoBundle:Default:index }

jcapote_to_do_complete:
    path:     /todo/complete/{id}
    defaults: { _controller: JcapoteToDoBundle:Default:complete }

jcapote_to_do_uncomplete:
    path:     /todo/uncomplete/{id}
    defaults: { _controller: JcapoteToDoBundle:Default:uncomplete }

jcapote_to_do_delete:
    path:     /todo/delete/{id}
    defaults: { _controller: JcapoteToDoBundle:Default:delete }
